import "server-only";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { AttachmentKind, Prisma } from "@/generated/prisma/client";
import { prisma } from "./prisma";
import { UserError } from "./action";

// Uploads live outside the build output; skip bundler tracing of this path.
const UPLOAD_DIR = path.resolve(/*turbopackIgnore: true*/ process.env.UPLOAD_DIR ?? path.join(process.cwd(), "uploads"));
const MAX_BYTES = 10 * 1024 * 1024;
const ALLOWED = /^(image\/(jpeg|png|webp|gif|heic|heif)|application\/pdf)$/;

type Owner = Omit<Prisma.AttachmentUncheckedCreateInput, "kind" | "storageKey" | "fileName" | "mimeType" | "sizeBytes" | "uploadedById">;

/** Save uploaded files to disk and create Attachment rows linked to `owner`. */
export async function saveAttachments(files: File[], kind: AttachmentKind, uploadedById: string, owner: Owner) {
  for (const f of files) {
    if (f.size > MAX_BYTES) throw new UserError(`${f.name} is larger than 10 MB`);
    if (!ALLOWED.test(f.type)) throw new UserError(`${f.name}: only images and PDF files are allowed`);
  }
  await mkdir(UPLOAD_DIR, { recursive: true });
  for (const f of files) {
    const ext = path.extname(f.name).toLowerCase().replace(/[^.a-z0-9]/g, "");
    const storageKey = `${randomUUID()}${ext}`;
    await writeFile(path.join(UPLOAD_DIR, storageKey), Buffer.from(await f.arrayBuffer()));
    await prisma.attachment.create({
      data: { ...owner, kind, storageKey, fileName: f.name, mimeType: f.type, sizeBytes: f.size, uploadedById },
    });
  }
}

export async function readAttachment(storageKey: string): Promise<Buffer> {
  // storageKey is generated by us, but guard against path tricks anyway.
  const file = path.join(UPLOAD_DIR, path.basename(storageKey));
  return readFile(file);
}
